spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nivara_db?useSSL=false&serverTimezone=UTC
    username: Badrinath
    password: Badri89@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
